# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := test-timer
ARDUINO_LIBS := AUnit AUnitVerbose
include ../../../EpoxyDuino/EpoxyDuino.mk
